-- Module Boîte à idées : tout membre connecté peut soumettre une idée, qui
-- reçoit un numéro de suivi séquentiel. Le bureau traite ensuite l'idée
-- (statut + réponse texte libre). L'auteur est toujours enregistré
-- (membre_id, jamais anonyme) mais la liste et les réponses sont visibles
-- de tous les membres authentifiés, comme pour le module votes.

CREATE TABLE idees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero_suivi INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  titre TEXT NOT NULL,
  description TEXT,
  membre_id UUID NOT NULL REFERENCES membres(id) ON DELETE CASCADE,
  statut TEXT NOT NULL DEFAULT 'nouvelle' CHECK (statut IN ('nouvelle', 'en_cours', 'acceptee', 'refusee', 'realisee')),
  reponse TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX ON idees (membre_id);

ALTER TABLE idees ENABLE ROW LEVEL SECURITY;

-- Lecture pour tout membre authentifié (transparence, comme les votes)
CREATE POLICY "idees_select" ON idees
  FOR SELECT TO authenticated USING (true);

-- Un membre ne peut soumettre une idée qu'en son propre nom
CREATE POLICY "idees_insert" ON idees
  FOR INSERT TO authenticated
  WITH CHECK (
    membre_id = (SELECT id FROM membres WHERE email = auth.jwt() ->> 'email' LIMIT 1)
  );

-- Seul le bureau change le statut / répond
CREATE POLICY "idees_update" ON idees
  FOR UPDATE TO authenticated
  USING (is_bureau(auth.jwt() ->> 'email'));

CREATE POLICY "idees_delete" ON idees
  FOR DELETE TO authenticated
  USING (is_bureau(auth.jwt() ->> 'email'));
